FROM openjdk:21-jre-slim

ARG SPRING_ACTIVE_PROFILE
ENV SPRING_ACTIVE_PROFILE=${SPRING_ACTIVE_PROFILE}

WORKDIR /app
COPY build/libs/*.jar app.jar

EXPOSE 8080

# JVM 메모리 최적화 추가
ENTRYPOINT ["java", \
    "-Duser.timezone=Asia/Seoul", \
    "-DLog4jContextSelector=org.apache.logging.log4j.core.async.AsyncLoggerContextSelector", \
    "-Dspring.profiles.active=${SPRING_ACTIVE_PROFILE}", \
    "-XX:+UseContainerSupport", \
    "-XX:MaxRAMPercentage=75.0", \
    "-jar", "/app/app.jar"]