services:
  dalcoomi:
    image: ${DOCKER_HUB_USERNAME}/${DOCKER_HUB_REPOSITORY}:latest
    container_name: dalcoomi-spring-prod
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8080:8080"
    environment:
      SPRING_ACTIVE_PROFILE: ${SPRING_ACTIVE_PROFILE}
    volumes:
      - ../logs/spring:/logs
    depends_on:
      - redis
    networks:
      - dalcoomi-network

  redis:
    image: redis:7-alpine
    container_name: dalcoomi-redis-prod
    restart: unless-stopped
    volumes:
      - redis_data:/data
      - ./redis-prod.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - dalcoomi-network
    # 메모리 제한 (EC2 t2.micro 고려)
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

volumes:
  redis_data:
    driver: local

networks:
  dalcoomi-network:
    driver: bridge